name: Node CI

on:
  push:
    branches:
      - master

jobs:
  Component Library:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          npx yarn
          npx lerna bootstrap
      - name: Lint
        run: npx yarn workspace @nekton/component-library run lint
      - name: Build
        run: npx yarn workspace @nekton/component-library run compile
      - name: Unit tests
        run: npx yarn workspace @nekton/component-library test:unit
        env:
          CI: true

  Dive Log:
    runs-on: ubunto-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          npx yarn
          npx lerna bootstrap
      - name: Lint
        run: npx yarn workspace @nekton/dive-log run lint;
      - name: Build
        run: npx yarn workspace @nekton/dive-log run compile
      - name: Unit tests
        run: npx yarn workspace @nekton/dive-log test:unit
        env: