name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: action-lerna
      uses: m19c/action-lerna@1.0.0
    - name: Bootstrap Lerna
      run: |
        lerna run clean
        lerna run compile
