name: Node CI

on:
  push:
    branches:
      - master

jobs:
  component-library-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          npx yarn
          npx lerna bootstrap
      - name: Lint
        run: npx yarn workspace @nekton/component-library run lint
      - name: Build
        run: npx yarn workspace @nekton/component-library run compile
      - name: Unit tests
        run: npx yarn workspace @nekton/component-library test:unit
        env:
          CI: true

  dive-log-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          npx yarn
          npx lerna bootstrap
      - name: Lint
        run: npx yarn workspace @nekton/dive-log run lint;
      - name: Build
        run: npx yarn workspace @nekton/dive-log run compile
      - name: Unit tests
        run: npx yarn workspace @nekton/dive-log test:unit
        env:
          CI: true
